BASE-FEATURE-AUTH
VarquLabs/DolarBlueApp pull request #18
Opened 2024-06-08 16:30 UTC by EliasMP07

Se agrego las carpetas para el modulo de Autenticación. Y las clases base para domain.

2024-06-08 16:32 UTC, DarioPapucho approved these changes
The best structure🥵

2024-06-08 16:40 UTC, Deivid117 approved these changes

2024-06-08 16:53 UTC, varquhaz requested changes
Deje un par de comments.

2024-06-08 16:53 UTC, varquhaz commented on app/src/main/java/com/varqulabs/dolarblue/core/domain/UseCase.kt
> +sealed class Result<out T : Any> {
No seria de ayuda un Result.Loading ?
Como lo ven ustedes ?

2024-06-08 16:53 UTC, varquhaz commented on app/src/main/java/com/varqulabs/dolarblue/core/user/di/UserAuthModule.kt
> +object UserAuthModule {
space

2024-06-08 16:53 UTC, varquhaz commented on app/src/main/java/com/varqulabs/dolarblue/core/user/di/UserAuthModule.kt
> +
remove space

2024-06-08 16:53 UTC, varquhaz commented on app/src/main/java/com/varqulabs/dolarblue/core/domain/UseCase.kt
> +sealed class Result<out T : Any> {
Separemos esta clase de Result en un archivo aparte.kt

2024-06-08 16:53 UTC, varquhaz commented on app/src/main/java/com/varqulabs/dolarblue/core/domain/UseCase.kt
> +sealed class UseCaseException(
archivo aparte

2024-06-08 16:53 UTC, varquhaz commented on app/src/main/java/com/varqulabs/dolarblue/core/domain/UseCase.kt
> +sealed class UseCaseException(
creemos una carpeta en core/domain llamada /usecase y ahi metamos estos 3 archivos

2024-06-08 17:55 UTC, DarioPapucho commented on app/src/main/java/com/varqulabs/dolarblue/core/domain/UseCase.kt
> +sealed class Result<out T : Any> {
Ya le pase el codigo para eso, nos olvidamos incluirlo

2024-06-09 02:45 UTC, EliasMP07 commented on app/src/main/java/com/varqulabs/dolarblue/core/domain/UseCase.kt
> +sealed class UseCaseException(
Los 3 archivos creo o solo uno, la result dado que excepción lo veo mejor dejarlo allí con junto con UseCase.

2024-06-09 02:46 UTC, EliasMP07 commented on app/src/main/java/com/varqulabs/dolarblue/core/domain/UseCase.kt
> +sealed class UseCaseException(
![Captura de pantalla 2024-06-08 a la(s) 20 45 27](https://github.com/VarquLabs/DolarBlueApp/assets/117881469/9c901383-bba5-4632-967f-5d84209f9658)

2024-06-09 14:46 UTC, closed without merging