FEATURE - CONVERSIONS HISTORY LOGIC
VarquLabs/DolarBlueApp pull request #23
Opened 2024-06-15 18:27 UTC by Deivid117

Módulo Core
Data
- Se agregó la base de datos de room y el type converter para guardar local date time en room

Módulo History
Data
- Se agregaron los dao, entities y lógica del repository para obtener el historial de conversiones
Domain
- Se agregaron los modelos necesarios, repository y use case
Presentation
- Se cambió la interfaz de la pantalla de Conversion History, posteriormente se regresó a la interfaz original

[Tareas](https://trello.com/c/41WuSn5d)

2024-06-15 19:06 UTC, DarioPapucho commented
Tienes 53 cambios, entre ellos esta el merge que ya se realizo en la rama base de Elias y Yo.
Actualizaste tu rama develop y le hiciste rebase o merge de la rama trabajada a la nueva rama actualizada develop?
Quiza por eso es que te salen demasiados cambios

2024-06-16 15:29 UTC, EliasMP07 reviewed
Deje comentarios para revisar.

2024-06-16 15:29 UTC, eliasmp07 commented on app/src/main/java/com/varqulabs/dolarblue/history/data/local/database/dao/ConversionHistoryDao.kt
> +    fun getConversionsHistory(): List<ConversionsHistoryRelation>
Es mejor usar Flow en la base de datos Room(Si habra cambios en la base de datos)

2024-06-16 15:29 UTC, EliasMP07 commented on app/src/main/java/com/varqulabs/dolarblue/history/data/local/database/dao/ConversionHistoryDao.kt
> +    fun getConversionsHistory(): Flow<List<ConversionsHistoryRelation>>
Si los habrá cambios constantes se le pondrá al nombre Flow al final y se usara flow, sin no abra cambios se manejara Listas dado que no abra cambios en la base de datos y no se estaba escuchando.

2024-06-16 15:29 UTC, EliasMP07 commented on app/src/main/java/com/varqulabs/dolarblue/history/data/local/database/entities/relations/ConversionsHistoryRelation.kt
> +fun ConversionsHistoryRelation.mapToModel() = ConversionsHistory(
Se movera a un carpeta llamada mappers en data, se creara un archivo que contenga los mappers de ConversionsHistory por ejemplo: ConversionsHistoryRelationMapper

2024-06-16 15:29 UTC, varquhaz requested changes
Deje un par de comentarios

2024-06-16 15:29 UTC, juanjosevarqu commented on app/src/main/java/com/varqulabs/dolarblue/core/data/local/database/converters/DBTypeConverter.kt
> +    fun toDate(dateString: String?): LocalDateTime? {
toLocalDateTime

2024-06-16 15:29 UTC, juanjosevarqu commented on app/src/main/java/com/varqulabs/dolarblue/history/data/local/database/dao/ConversionDao.kt
> +// TODO @Deivid - mover el dao al módulo de calculadora
Podemos moverlo de una vez al modulo de calculadora porfa

2024-06-16 15:29 UTC, varquhaz commented on app/src/main/java/com/varqulabs/dolarblue/history/domain/model/Conversion.kt
> +import java.time.LocalDateTime
En el proximo PR, junto con el Reemplazo de KSP, hagamos el reemplazo de Kotlin LocalDateTime porfa

2024-06-16 15:29 UTC, varquhaz commented on app/src/main/java/com/varqulabs/dolarblue/history/data/local/database/dao/ConversionDao.kt
> +    @Insert()
usemos el onConflict REPLACE plox

2024-06-16 15:29 UTC, varquhaz commented on app/src/main/java/com/varqulabs/dolarblue/history/data/local/database/dao/ConversionHistoryDao.kt
> +    fun getConversionsHistory(): Flow<List<ConversionsHistoryRelation>>
creemos una funcion auxiliar que no dependa del Flow, para operaciones que solo requieran ser llamadas una sola vez

2024-06-16 15:29 UTC, varquhaz commented on app/src/main/java/com/varqulabs/dolarblue/history/data/local/database/dao/CurrentExchangeRateDao.kt
> +// TODO @Deivid - mover el dao al módulo de calculadora
.

2024-06-16 15:29 UTC, varquhaz commented on app/src/main/java/com/varqulabs/dolarblue/history/data/local/database/entities/ConversionEntity.kt
> +// TODO: @Deivid - mover el entity al módulo de calculadora
.

2024-06-16 16:55 UTC, varquhaz reviewed
Falto el Renombre de la funcion de Parseador de Fecha

2024-06-16 16:55 UTC, varquhaz commented on app/src/main/java/com/varqulabs/dolarblue/core/data/local/database/converters/DBTypeConverter.kt
> +    fun toDate(dateString: String?): LocalDateTime? {
?

2024-06-16 17:14 UTC, varquhaz approved these changes

2024-06-16 17:17 UTC, EliasMP07 approved these changes

2024-06-16 17:23 UTC, merged