FEATURE - SETTINGS - Common Composables & Refactor Constants
VarquLabs/DolarBlueApp pull request #25
Opened 2024-06-16 20:15 UTC by varquhaz

[Settings - Presentation](https://trello.com/c/dpDhdLr0)
NO-TASK - Se Agregaron componentes Comunes como el del Loading y los Item para el Drawer

![Screenshot 2024-06-16 at 16 15 06](https://github.com/VarquLabs/DolarBlueApp/assets/135390925/9b868c2f-4351-41ac-858e-97fd624aebbd)

2024-06-16 21:30 UTC, Deivid117 approved these changes

2024-06-23 17:50 UTC, DarioPapucho requested changes
Deje un par de comentarios respecto a las comas despues del ultimo parametro

2024-06-23 17:50 UTC, DarioPapucho commented on app/src/main/java/com/varqulabs/dolarblue/core/presentation/generics/top_bars/DrawerAppBar.kt
> +    onClickDrawer: () -> Unit,
Se acordo quitar las comas despues del ultimo parametro

2024-06-23 17:50 UTC, DarioPapucho commented on app/src/main/java/com/varqulabs/dolarblue/core/presentation/model/DrawerItem.kt
> +    val route: Routes,
Se acordo quitar las comas despues del ultimo parametro

2024-06-23 18:06 UTC, DarioPapucho approved these changes

2024-06-23 18:09 UTC, merged