FEATURE - HISTORY - Add & Get conversions favorites
VarquLabs/DolarBlueApp pull request #38
Opened 2024-06-29 16:15 UTC by Deivid117

- Se agregó la lógica para marcar una conversión como favorita
- Se agregó la lógica para obtener todas las conversiones marcadas como favoritas
- También se aumentó en 2 puntos el tamaño de la fuente bodyLarge

[Tareas](https://trello.com/c/DXfSsWQa)

2024-06-29 17:09 UTC, varquhaz requested changes
Deje una review

2024-06-29 17:09 UTC, varquhaz commented on app/src/main/java/com/varqulabs/dolarblue/history/data/repository/ConversionsHistoryRepositoryImpl.kt
> +    private fun groupByExchangeRateIdAndMapToConversionHistory(daoFunction: Flow<List<ConversionsWithCurrentExchangeRelation>>) : Flow<List<ConversionsHistory>> {
Podemos buscar un nombre mas simple para esta funcion

El "groupBy" lo hace dentro, pero puede que en el futuro encontremos otra forma. O directo en el Query

2024-06-29 17:09 UTC, varquhaz commented on app/src/main/java/com/varqulabs/dolarblue/history/data/local/database/dao/ConversionsHistoryDao.kt
> +    fun addConversionFavorite(conversionId: Int, isFavorite: Boolean)
Podria llamarse addConversionToFavorites

2024-06-29 17:09 UTC, varquhaz commented on app/src/main/java/com/varqulabs/dolarblue/history/domain/useCases/AddConversionFavoriteUseCase.kt
> +class AddConversionFavoriteUseCase(
X2

2024-06-29 17:09 UTC, varquhaz commented on app/src/main/java/com/varqulabs/dolarblue/history/domain/useCases/AddConversionFavoriteUseCase.kt
> +    suspend operator fun invoke(conversionId: Int, isFavorite: Boolean) {
Es necesario el parametro isFavorite ?
El Caso de Uso da a entender que se agregara a Favoritos

2024-06-29 17:12 UTC, varquhaz commented on app/src/main/java/com/varqulabs/dolarblue/history/domain/useCases/AddConversionFavoriteUseCase.kt
> +    suspend operator fun invoke(conversionId: Int, isFavorite: Boolean) {
La Validación de si es Favorito o no para llamar al caso de uso, puede hacerse en el ViewModel

2024-06-29 17:42 UTC, Deivid117 commented on app/src/main/java/com/varqulabs/dolarblue/history/data/repository/ConversionsHistoryRepositoryImpl.kt
> +    private fun groupByExchangeRateIdAndMapToConversionHistory(daoFunction: Flow<List<ConversionsWithCurrentExchangeRelation>>) : Flow<List<ConversionsHistory>> {
¿Alguna otra propuesta? No se me ocurrió otra idea para el nombre?

2024-06-29 17:45 UTC, Deivid117 commented on app/src/main/java/com/varqulabs/dolarblue/history/domain/useCases/AddConversionFavoriteUseCase.kt
> +    suspend operator fun invoke(conversionId: Int, isFavorite: Boolean) {
Con ese mismo pretendo que sirva tanto para marcar como favorito como para quitarlo de favoritos en un solo caso de uso, no sé si pueda ir otro nombre para ambas acciones

2024-06-29 20:37 UTC, varquhaz commented on app/src/main/java/com/varqulabs/dolarblue/history/domain/mappers/ConversionMapper.kt
> +fun Conversion.mapToEntity() = ConversionEntity(
Reformat y name paremeters

2024-06-29 20:52 UTC, varquhaz approved these changes

2024-06-30 15:01 UTC, EliasMP07 approved these changes

2024-06-30 15:01 UTC, merged